export enum CrunchyPlayStreams {
    'chrome'    = 'web/chrome',
    'firefox'   = 'web/firefox',
    'safari'    = 'web/safari',
    'edge'      = 'web/edge',
    'fallback'  = 'web/fallback',
    'ps4'       = 'console/ps4',
    'ps5'       = 'console/ps5',
    'switch'    = 'console/switch',
    'xboxone'   = 'console/xbox_one',
    'vidaa'     = 'tv/vidaa',
    'samsungtv' = 'tv/samsung',
    'lgtv'      = 'tv/lg',
    'rokutv'    = 'tv/roku',
    'android'   = 'android/phone',
    'androidt'  = 'android/tablet',
    'iphone'    = 'ios/iphone',
    'ipad'      = 'ios/ipad',
    'vision'    = 'ios/vision',
}