// Generated by https://quicktype.io

export interface SubtitleRequest {
  primary:  Primary;
  fallback: Primary[];
}

export interface Primary {
  venueVideoId:     string;
  alphaPackageId:   string;
  versionContentId: VersionContentID;
  manifestPath:     string;
  fileExt:          PrimaryFileEXT;
  subtitles:        Subtitle[];
  accessType:       AccessType;
  sessionId:        string;
  audioLanguage:    AudioLanguage;
  version:          Version;
  aips:             Aip[];
  drmToken:         string;
  drmType:          string;
}

export enum AccessType {
  Subscription = 'subscription',
}

export interface Aip {
  in:  number;
  out: number;
}

export enum AudioLanguage {
  En = 'en',
  Ja = 'ja',
}

export enum PrimaryFileEXT {
  M3U8 = 'm3u8',
  Mp4 = 'mp4',
}

export interface Subtitle {
  filePath:     string;
  fileExt:      SubtitleFileEXT;
  contentType:  ContentType;
  languageCode: LanguageCode;
}

export enum ContentType {
  Cc = 'cc',
  Full = 'full',
}

export enum SubtitleFileEXT {
  Dfxp = 'dfxp',
  Srt = 'srt',
  Vtt = 'vtt',
}

export enum LanguageCode {
  En = 'en',
  Es = 'es',
  Pt = 'pt',
}

export enum Version {
  Simulcast = 'simulcast',
  Uncut = 'uncut',
}

export enum VersionContentID {
  Akusim0012 = 'AKUSIM0012',
  Akuunc0012 = 'AKUUNC0012',
}
