// Generated by https://quicktype.io

export interface FunimationSearch {
  count:  number;
  items:  Items;
  limit:  string;
  offset: string;
}

export interface Items {
  hits: Hit[];
}

export interface Hit {
  ratings:     string;
  description: string;
  title:       string;
  image:       {
    showThumbnail: string,
    [key: string]: string 
  };
  starRating:  number;
  slug:        string;
  languages:   string[];
  synopsis:    string;
  quality:     Quality;
  id:          string;
  txDate:      number;
}

export interface Quality {
  quality: string;
  height:  number;
}
