// Generated by https://quicktype.io

export interface PlaybackData {
  audio_locale: string;
  subtitles:    { [key: string]: Subtitle };
  streams:      { [key: string]: { [key: string]: Stream } };
  QoS:          QoS;
}

export interface QoS {
  region:              string;
  cloudFrontRequestId: string;
  lambdaRunTime:       number;
}

export interface Stream {
  hardsub_locale: string;
  url:            string;
  vcodec:         Vcodec;
  hardsub_lang?:  string;
  audio_lang?:    string;
  type?:          string;
}


export enum Vcodec {
  H264 = 'h264',
}

export interface Subtitle {
  locale: Locale;
  url:    string;
  format: string;
}
